#:import menu menu

MainWidget:
    

<MainWidget>:
    canvas.before: 
        Rectangle: 
            size: self.size
            source: 'images/bg1.jpg'
    menu_widget: menu_widget
    perspective_point_X: self.width/2
    perspective_point_y: self.height*0.75
    MenuWidget:
        id: menu_widget
    Label:
        text: root.score_txt
        font_size: dp(15)
        font_name: 'fonts/PoeGalaxy-zMrD.ttf'
        size_hint: .1, .1
        pos_hint: {"x": .70, "top": 1}